version: 2.1

executors: 
  my-executor:
    docker:
      - image: circleci/rust:latest
jobs:
  checkout code:
    executor: my-executor   
    steps:
      - checkout
      - run: rustup default nightly
  build:
    executor: my-executor
    steps:
      -run:
        command: cargo build
  check formatting: 
    executor: my-executor
    steps:
      - run:
          command: cargo fmt
  test:
    executor: my-executor
    steps:
      - run:
          command: cargo test
workflows:
  checkout and formatting:
    jobs:
      - checkout code
      - check formatting:
        requires:
          - checkout
  TU and build:
    jobs:
      - check formatting
      - build:
        requires:
          - build