version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/rust:latest

jobs:
  checkoutCode:
    executor: my-executor
    steps:
      - checkout
      - run: rustup default nightly

  build:
    executor: my-executor
    steps:
      - run: cargo build

  checkFormatting:
    executor: my-executor
    steps:
      - run: 
        commande: |
          rustup component add rustfmt
          cargo fmt

  test:
    executor: my-executor
    steps:
      - run: cargo test

workflows:
  version: 2

  Format_Test_Build:
    jobs:
      - checkoutCode
      - checkFormatting:
          requires:
            - checkoutCode
      - test:
          requires:
            - checkFormatting
      - build:
          requires:
            - test
