version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/rust:latest
    working_directory: /tmp

jobs:
  checkoutCode:
    executor: my-executor
    steps:
      - run: mkdir api
      - run: cd api
      - checkout
      - run: rustup default nightly
      - persist_to_workspace:
          root: api
          paths:
            - src


  build:
    executor: my-executor
    steps:
      - attach_workspace: 
          at: /tmp/api
      - run: cargo build

  checkFormatting:
    executor: my-executor
    steps:
      - attach_workspace: 
          at: /tmp/api
      - run:
          command: |
            rustup component add rustfmt
            cargo fmt

  test:
    executor: my-executor
    steps:
      - attach_workspace: 
          at: /tmp/api
      - run: cargo test

workflows:
  version: 2

  Format_Test_Build:
    jobs:
      - checkoutCode
      - checkFormatting:
          requires:
            - checkoutCode
      - test:
          requires:
            - checkFormatting
      - build:
          requires:
            - test
