version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest
      
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name : Clippy lint
          command : cargo run --bin cargo-clippy --manifest-path=path_to_clippys_Cargo.toml
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"